version: "3"

services:
  web:
    build:
      context: .
      target: web
    container_name: web
    ports:
      - "80:80"

  mysql:
    build:
      context: .
      target: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"

volumes:
  dbdata:
